language: node_js
node_js:
  - "6"
os:
  - osx
cache:
  - yarn
  - directories:
    - "$TRAVIS_BUILD_DIR/node_modules"
    - "$TRAVIS_BUILD_DIR/Example/node_modules"

notifications:
  email: false

branches:
  only:
    - master
    - ci-test

before_script:
  - cd Example && yarn && cd ..

script:
  - node node_modules/eslint/bin/eslint index.js src/ test/
  - yarn test
  - cd Example && yarn run jest && cd ..
