language: node_js
node_js:
  - "6"
os:
  - osx
cache:
  - yarn
  - directories:
    - "$TRAVIS_BUILD_DIR/node_modules"
    - "$TRAVIS_BUILD_DIR/Example/node_modules"

notifications:
  email: false

branches:
  only:
    - master
    - ci-test
before_install:
  - export YARN_GPG=no
install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - cd Example && yarn && cd ..
  - yarn

before_script:
  - rm -rf Example/node_modules/react-native-router-flux/node_modules
  - cp -r src/ Example/node_modules/react-native-router-flux/src/
  - cat src/Util.js
  - cat Example/node_modules/react-native-router-flux/src/Util.js

script:
  - node node_modules/eslint/bin/eslint index.js src/ test/
  - yarn test
  - cd Example && yarn run jest && cd ..
