language: node_js
node_js:
  - "6"
cache:
  - yarn
  - directories:
    - "$TRAVIS_BUILD_DIR/Example/node_modules"

notifications:
  email: false

branches:
  only:
    - master
    - ci-test

before_script:
  - yarn
  - cd Example && yarn && cd ..
